pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Semgrep Scan - Multiple repos
        identifier: Semgrep_Scan_Multiple_repos
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Semgrep_Scan
                  identifier: Semgrep_Scan
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          #!/bin/bash

                          # Step 1: Install Python and Pip using microdnf
                          echo "Installing Python and Pip using microdnf..."
                          microdnf install -y python39 python39-pip git
                          microdnf clean all

                          # Step 2: Install Semgrep using pip
                          echo "Installing Semgrep..."
                          pip3 install semgrep

                          # Step 3: Verify Semgrep installation
                          echo "Verifying Semgrep installation..."
                          semgrep --version

                          # Step 4: Define an associative array of orgs and repos
                          declare -A orgs_and_repos=(
                              ["harness"]="ff-proxy lite-engine"
                              ["drone"]="drone-jira drone-plugin-index"
                              ["takipi"]="takipi-storage"
                          )

                          # Step 5: Function to clone the default branch, print the default branch, run Semgrep, and print results summary
                          scan_repo() {
                              local org=$1
                              local repo=$2

                              echo "Scanning repo: ${org}/${repo}"

                              # Clone the repository
                              git clone https://github.com/${org}/${repo}.git
                              cd ${repo} || exit 1

                              # List contents of the cloned repo
                              echo "Contents of ${repo}:"
                              ls

                              # Fetch the default branch
                              default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

                              # Print the default branch
                              echo "Default branch for ${repo} is ${default_branch}"

                              # Checkout the default branch
                              git checkout $default_branch

                              # Run Semgrep on the default branch and store results in SARIF format
                              result_file="../${repo}_results.sarif"
                              semgrep ci --config auto --sarif -o $result_file

                              # Print the SARIF results file path
                              echo "Completed scanning ${repo}. Results stored in ${result_file}"

                              # Print summary of the scan
                              if [ -f "$result_file" ]; then
                                  issues_count=$(jq '.runs[0].results | length' $result_file)
                                  echo "Summary for ${repo}:"
                                  echo "Total issues found: $issues_count"
                                  if [ "$issues_count" -gt 0 ]; then
                                      jq -r '.runs[0].results[] | "Rule: \(.ruleId), Severity: \(.level), Message: \(.message.text)"' $result_file
                                  fi
                              else
                                  echo "No results file generated for ${repo}"
                              fi

                              # Move back to the parent directory and clean up
                              cd ..
                              echo "Cleaning up cloned repo: ${repo}"
                              rm -rf ${repo}

                              # List all the cloned repositories after each scan
                              echo "Listing all cloned repositories and results:"
                              ls
                          }

                          # Step 6: Loop through each org and its repos
                          for org in "${!orgs_and_repos[@]}"; do
                              repos=${orgs_and_repos[$org]}
                              for repo in $repos; do
                                  scan_repo $org $repo
                              done
                          done

                          # Step 7: List all repositories and their results
                          echo "Final list of all repositories and Semgrep result files:"
                          ls
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
